#linux specific settings
COMMANDS += containerd-shim

# amd64 supports go test -race
ifeq ("amd64", $(GOARCH))
	TESTFLAGS_RACE= -race
endif

# arm64 does not support go lint
arch=arm64
ifeq ($(arch), $(GOARCH))
	LINT=
endif
